import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; 
import "./public/assets/vendor/aos/aos.css";
// vendor/aos/aos.css"
// import "../../public/assets/vendor/bootstrap/css/bootstrap-grid.min.css";
// import "../../public/assets/vendor/bootstrap-icons/bootstrap-icons.css";

// import "../../public/assets/vendor/glightbox/css/glightbox.min.css";
// import "../../public/assets/vendor/swiper/swiper-bundle.min.css";
// import "../../public/assets/vendor/swiper/swiper-bundle.min.css";
// import "../../public/assets/vendor/bootstrap/js/bootstrap.bundle.min.js";
// import "../../public/assets/vendor/php-email-form/validate.js";
// import "../../public/assets/vendor/aos/aos.js";
// import "../../public/assets/vendor/typed.js/typed.umd.js";
// import "../../public/assets/vendor/purecounter/purecounter_vanilla.js";
// import "../../public/assets/vendor/waypoints/noframework.waypoints.js";
// import "../../public/assets/vendor/glightbox/js/glightbox.min.js";
// import "../../public/assets/vendor/imagesloaded/imagesloaded.pkgd.min.js";
// import "../../public/assets/vendor/isotope-layout/isotope.pkgd.min.js";
// import "../../public/assets/vendor/swiper/swiper-bundle.min.js";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Apps",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
